"""
Report generation endpoints.

Provides comprehensive session report as JSON, mirroring the
final report generated by the CLI main.py.
"""

from __future__ import annotations

from typing import Any

from fastapi import APIRouter, HTTPException

from web.core.state import get_app_state

router = APIRouter()


# ---------------------------------------------------------------------------
# Report sections
# ---------------------------------------------------------------------------

REPORT_SECTIONS = [
    "session", "blockchain", "agents", "devices",
    "governance", "offchain", "health", "conflicts",
]


def _require_active_session():
    """Raise 400 if no active session."""
    state = get_app_state()
    if not state.is_active:
        raise HTTPException(
            status_code=400,
            detail="No active session.",
        )
    return state


def _build_session_section(state) -> dict[str, Any]:
    """Session metadata."""
    return {
        "session_name": state.session_name,
        "is_fresh": state.is_fresh,
    }


def _build_blockchain_section(state) -> dict[str, Any]:
    """Blockchain summary."""
    chain = state.chain
    if not chain:
        return {"error": "Blockchain not initialized"}

    total_tx = sum(len(b.transactions) for b in chain.chain)
    tx_types = {}
    for b in chain.chain:
        for tx in b.transactions:
            tx_types[tx.tx_type] = tx_types.get(tx.tx_type, 0) + 1

    return {
        "total_blocks": len(chain.chain),
        "total_transactions": total_tx,
        "pending_transactions": len(chain.pending_tx),
        "rejected_transactions": len(chain.rejected_tx),
        "chain_valid": chain.validate_chain(),
        "transaction_types": tx_types,
        "registered_agents": len(chain.registry._agents),
        "adaptive_pow": chain.adaptive.get_stats(),
    }


def _build_agents_section(state) -> dict[str, Any]:
    """Agent information."""
    from engine.config import AGENT_DEFINITIONS

    agents = []
    for agent_id, defn in AGENT_DEFINITIONS.items():
        priority = defn["priority"]
        if state.chain:
            priority = state.chain.priorities.get_priority(agent_id)

        stats = {}
        if state.store:
            try:
                stats = state.store.get_outcome_stats(agent_id)
            except Exception:
                pass

        agents.append({
            "agent_id": agent_id,
            "role": defn["role"],
            "priority": priority,
            "model": defn.get("model", "n/a"),
            "decision_stats": stats,
        })

    return {
        "total_agents": len(agents),
        "agents": agents,
    }


def _build_devices_section(state) -> dict[str, Any]:
    """Device information."""
    if not state.mcp:
        return {"error": "MCP not initialized"}

    try:
        devices = state.mcp.list_devices()
        return {
            "total_devices": len(devices),
            "devices": devices,
        }
    except Exception as e:
        return {"error": str(e)}


def _build_governance_section(state) -> dict[str, Any]:
    """Governance state."""
    result = {}

    if state.preferences:
        result["preferences"] = state.preferences.to_dict()

    if state.model_router:
        result["model_assignments"] = state.model_router.get_all_assignments()

    if state.gov_contract:
        result["preference_changes"] = state.gov_contract.preference_changes
        result["model_changes"] = state.gov_contract.model_changes
        result["change_log_count"] = len(state.gov_contract.change_log)

    if state.store:
        try:
            result["offchain_stats"] = state.store.get_governance_stats()
        except Exception:
            pass
        try:
            result["model_usage"] = state.store.get_model_usage_stats()
        except Exception:
            pass

    return result


def _build_offchain_section(state) -> dict[str, Any]:
    """Off-chain store summary."""
    if not state.store:
        return {"error": "Store not initialized"}

    try:
        return state.store.stats()
    except Exception as e:
        return {"error": str(e)}


def _build_health_section(state) -> dict[str, Any]:
    """MCP health summary."""
    if not state.store:
        return {"error": "Store not initialized"}

    try:
        return state.store.get_health_summary()
    except Exception as e:
        return {"error": str(e)}


def _build_conflicts_section(state) -> dict[str, Any]:
    """Conflict resolution summary."""
    if not state.store:
        return {"error": "Store not initialized"}

    try:
        conflicts = state.store.query_conflicts()
        conflict_stats = state.store.conflict_stats()
        return {
            "total_conflicts": len(conflicts),
            "stats": conflict_stats,
        }
    except Exception as e:
        return {"error": str(e)}


_SECTION_BUILDERS = {
    "session": _build_session_section,
    "blockchain": _build_blockchain_section,
    "agents": _build_agents_section,
    "devices": _build_devices_section,
    "governance": _build_governance_section,
    "offchain": _build_offchain_section,
    "health": _build_health_section,
    "conflicts": _build_conflicts_section,
}


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("/")
def get_full_report() -> dict[str, Any]:
    """Generate comprehensive session report (all sections)."""
    state = _require_active_session()

    report = {}
    for section_name, builder in _SECTION_BUILDERS.items():
        try:
            report[section_name] = builder(state)
        except Exception as e:
            report[section_name] = {"error": str(e)}

    return {"report": report, "sections": list(report.keys())}


@router.get("/{section}")
def get_report_section(section: str) -> dict[str, Any]:
    """Get a specific report section."""
    state = _require_active_session()

    builder = _SECTION_BUILDERS.get(section)
    if not builder:
        raise HTTPException(
            status_code=404,
            detail=(
                f"Unknown report section '{section}'. "
                f"Available: {', '.join(REPORT_SECTIONS)}"
            ),
        )

    try:
        data = builder(state)
    except Exception as e:
        raise HTTPException(
            status_code=500, detail=f"Report section error: {e}"
        )

    return {"section": section, "data": data}
